name: catgpt
run-name: ${{ github.actor }} is building catgpt
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build bin
        uses: docker/build-push-action@v5